name: "PR Review to AGENTS.md"
description: "Automatically updates AGENTS.md documentation based on PR review comments using AI"
author: "Carson Farmer"

branding:
  icon: "file-text"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for API access"
    required: true
    default: ${{ github.token }}
  anthropic-api-key:
    description: "Anthropic API key for Claude"
    required: true
  model:
    description: "Claude model to use"
    required: false
    default: "claude-sonnet-4-5-20250929"
  doc-file:
    description: "Documentation file to update"
    required: false
    default: "AGENTS.md"

runs:
  using: "composite"
  steps:
    - name: Check if PR modifies doc file
      id: check_files
      shell: bash
      run: |
        files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')

        if echo "$files" | grep -q "^${{ inputs.doc-file }}$"; then
          echo "skip=true" >> $GITHUB_OUTPUT
          echo "Skipping: PR modifies ${{ inputs.doc-file }} (avoiding review loop)"
        else
          echo "skip=false" >> $GITHUB_OUTPUT
        fi
      env:
        GH_TOKEN: ${{ inputs.github-token }}

    - name: Setup Node.js
      if: steps.check_files.outputs.skip != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install dependencies
      if: steps.check_files.outputs.skip != 'true'
      shell: bash
      run: npm install @octokit/rest ai @ai-sdk/anthropic

    - name: Update docs from review comments
      if: steps.check_files.outputs.skip != 'true'
      shell: bash
      run: node ${{ github.action_path }}/scripts/update-docs-from-review.js
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        LLM_MODEL: ${{ inputs.model }}
        DOC_FILE: ${{ inputs.doc-file }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPOSITORY: ${{ github.repository }}
        REVIEW_BODY: ${{ github.event.review.body }}
        REVIEW_STATE: ${{ github.event.review.state }}

    - name: Create Pull Request with documentation updates
      if: steps.check_files.outputs.skip != 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.github-token }}
        commit-message: |
          docs: Update ${{ inputs.doc-file }} from PR #${{ github.event.pull_request.number }} review

          Automated update based on review comments.

          Source PR: #${{ github.event.pull_request.number }}
        branch: update-${{ inputs.doc-file }}-pr-${{ github.event.pull_request.number }}
        delete-branch: true
        title: "docs: Update ${{ inputs.doc-file }} from PR #${{ github.event.pull_request.number }} review"
        body: |
          Automated documentation update based on review comments from PR #${{ github.event.pull_request.number }}.

          **Source PR:** #${{ github.event.pull_request.number }}
          **Reviewer:** @${{ github.event.review.user.login }}

          This PR updates `${{ inputs.doc-file }}` with insights from the review discussion.
        labels: documentation, automated
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
